#!/usr/bin/env python3

import sys

def print_args():
    script = sys.argv[0]
    print(f"The name of the script is {script}")
    if len(sys.argv) > 1:
        args = " ".join(sys.argv[1:])
        print(f"The name of the script and the arguments passed are: {script} {args}")
    else:
        print("No arguments were passed to the script.")

def helloWorld():
   print('Hello World')

helloWorld()
